[theme]
primaryColor = "#1E90FF"         # Main accent (buttons, sliders, progress bars)
backgroundColor = "#FFFFFF"      # App background
secondaryBackgroundColor = "#E6F0FA"  # Sidebar & widgets background
textColor = "#000000"            # Main text color
font = "sans serif"              # Font style
